### ISSUE TITLE
"issueベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by Itok1000** [Itok1000/master#38]
■Webアプリの概要
ガマルジョバはおすすめのジョージア料理を紹介して作り方のサイトに遷移、
Xで共有できるジョージア料理診断サービスWebアプリです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：最小 26時間、最大42時間

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
:issue
https://github.com/users/Itok1000/projects/1/views/1

■MVPリリースまで
- [x] rails new(CSS:bootstrapにて環境構築済み)
- [x] fly.ioにデプロイ
- [x] トップページ
- [x] 診断機能（未ログインでも閲覧可能)
- [x] 診断結果を表示機能（未ログインでも閲覧可能）
- [x] Xにて共有機能（未ログインでも閲覧可能）
- [x] サイトに遷移機能（未ログインでも閲覧可能）
- [x] ログイン機能
- [x] コメント投稿機能
- [x] コメント閲覧機能
- [ ] レーティング機能

■MVP後
- [x] 利用規約
- [x] プライバシーポリシー
- [x] お問い合わせ
- [x] パスワードリセット機能
- [x] パスワード更新

■MVPレビュー依頼予定日
予定日：2024年 11月 8日

**Comment by Itok1000** [comment]
1点質問です
>作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

ここでいう看板というのはREADMEであり、ストーリーポイントは画面遷移図とER図の認識で間違いないでしょうか？

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

---

> ここでいう看板というのはREADMEであり、ストーリーポイントは画面遷移図とER図の認識で間違いないでしょうか？

看板というのはprojectsのBaordなどを指す言葉になります。
ストーリーポイントはカリキュラムに記載されている内容をご確認ください。

**Comment by Itok1000** [comment]
>ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
>カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。

ストーリーポイントの意味をはき違えてました
修正いたしましたので、再度ご確認をお願いいたします

1点質問です

MVPレビュー時と画像遷移図が異なる場合(ヘッダーの色変更など)はMVPレビュー時に再度提出の認識でしょうか？

**Comment by kenchasonakai** [comment]
LGTMです！

> MVPレビュー時と画像遷移図が異なる場合(ヘッダーの色変更など)はMVPレビュー時に再度提出の認識でしょうか？

画面がもともと想定していたものと変わるのは特に問題ないので画面遷移図レビューの再提出は不要です

**Comment by Itok1000** [comment]
承知しました
ありがとうございました
